name: checklist
description: A Simple app to quickly manage checklists.
version: 1.0.0+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^0.6.1
  uuid: ^2.0.2
  rxdart: ^0.22.3
  provider: ^3.1.0
  intl: ^0.16.0
  dio: ^3.0.3
  localstorage: ^3.0.0+2
  kiwi: ^0.2.0
  flutter_bloc: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.7.2
  kiwi_generator: ^0.4.0

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: lib/assets/fonts/OpenSans-Regular.ttf

  assets:
    - lib/assets/configuration.json
